spring:
    datasource:
        password: brubix
        url: jdbc:mysql://localhost:3306/brubix
        username: brubix
    jpa:
        hibernate:
            ddl-auto: create

server:
    context-path: /v1
    port: 8080
