spring:
    datasource:
        driver-class-code: com.mysql.cj.jdbc.Driver
        password: brubix
        url: jdbc:mysql://localhost:3306/brubix
        username: brubix
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
server:
    context-path: /v1
    port: 8090

brubix:
    oauth:
        token:
            timeout: 1800
        refresh-token:
            timeout: 3600