spring:
    datasource:
        driver-class-code: com.mysql.cj.jdbc.Driver
        password: brubix
        url: jdbc:mysql://localhost:3306/brubix
        username: brubix
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
server:
    context-path: /v1
    port: 8081

brubix:
    oauth:
        token:
            timeout: 120
        refresh-token:
            timeout: 3600
security:
    signing-key: BrubixIsAwesome