spring:
    datasource:
        driver-class-code: com.mysql.cj.jdbc.Driver
        password: brubix
        url: jdbc:mysql://localhost:3306/brubix
        username: brubix
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
    http:
        multipart:
            max-file-size: 1024KB
            max-request-size: 1500KB

server:
    context-path: /v1
    port: 8080

hibernate:
    validator:
        fail-fast: false

